# Generated by Django 6.0.2 on 2026-05-26 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.IntegerField()),
                ('place_type', models.CharField(choices=[('Hill', 'Hill'), ('Mountain', 'Mountain'), ('Beach', 'Beach'), ('Forest', 'Forest')], max_length=20)),
                ('weather', models.CharField(choices=[('Cool', 'Cool'), ('Hot', 'Hot')], max_length=20)),
                ('days', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
