# Generated by Django 6.0.2 on 2026-05-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelpreference',
            name='place_type',
            field=models.CharField(choices=[('Hill', 'Hill'), ('Mountain', 'Mountain'), ('Beach', 'Beach'), ('Forest', 'Forest'), ('Temple', 'Temple'), ('Historical', 'Historical'), ('Adventure', 'Adventure')], max_length=20),
        ),
    ]
